name: Run External SFTP Poller
description: Run the external SFTP poller to get files from an external SFTP server and log any failures to Slack

inputs:
  customer_isa_id:
    description: The ISA ID of the customer, which is set up as the key to the external SFTP poller configuration
    required: true

  stedi_api_key:
    description: The API key for the Stedi user
    required: true

  destination_webhook_url:
    description: The webhook URL for the destination
    required: true

  executions_bucket_name:
    description: The name of the bucket where the executions are stored
    required: true

  sftp_bucket_name:
    description: The name of the bucket where the SFTP files are stored
    required: true

  slack_webhook_url:
    description: The webhook URL for the Slack channel
    required: true

runs:
  using: composite
  steps:
    - name: Run SFTP Poller
      shell: bash
      run: npm run execute ftp-external-poller ${{ inputs.customer_isa_id }}
      env:
        STEDI_API_KEY: ${{ inputs.stedi_api_key }}
        DESTINATION_WEBHOOK_URL: ${{ inputs.destination_webhook_url }}
        EXECUTIONS_BUCKET_NAME: ${{ inputs.executions_bucket_name }}
        SFTP_BUCKET_NAME: ${{ inputs.sftp_bucket_name }}

    - if: failure()
      name: Notify Slack Of Failure
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Warning* :warning:"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The SFTP poller failed its run. [<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action Run ${{ github.run_id }}>]"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK