name: Run External SFTP Poller
description: Run the external SFTP poller to get files from an external SFTP server and log any failures to Slack

inputs:
  customer_isa_id:
    description: The ISA ID of the customer, which is set up as the key to the external SFTP poller configuration
    required: true

runs:
  using: composite
  steps:
    - name: Run SFTP Poller
      shell: bash
      run: npm run execute ftp-external-poller ${{ inputs.customer_isa_id }}
      env:
        STEDI_API_KEY: ${{secrets.STEDI_API_KEY}} # this is the API key for the Stedi user
        DESTINATION_WEBHOOK_URL: ${{secrets.DESTINATION_WEBHOOK_URL}} # something that doesn't need to be changed it seems
        EXECUTIONS_BUCKET_NAME: ${{secrets.EXECUTIONS_BUCKET_NAME }} # this is the bucket where the executions are stored
        SFTP_BUCKET_NAME: ${{secrets.SFTP_BUCKET_NAME }} # this is the bucket where the SFTP files are stored

    - if: failure()
      name: Notify Slack Of Failure
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Warning* :warning:"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The SFTP poller failed its run. [<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action Run ${{ github.run_id }}>]"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # this is the webhook URL for the Slack channel
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK