name: Scheduled External SFTP Poller

on:
  schedule:
    # run every 8 minutes (starting from 4 after each hour)
    - cron: "4/8 * * * *"

jobs:
  run_sftp_poller:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"
      - run: npm ci
      - run: npm run execute ftp-external-poller FMXCHEPT
        env:
          STEDI_API_KEY: ${{secrets.STEDI_API_KEY}}
          DESTINATION_WEBHOOK_URL: ${{secrets.DESTINATION_WEBHOOK_URL}}
          EXECUTIONS_BUCKET_NAME: ${{secrets.EXECUTIONS_BUCKET_NAME }}
          SFTP_BUCKET_NAME: ${{secrets.SFTP_BUCKET_NAME }}
      # notify via slack if any failures are encountered
      # - if: #${{ failure() }}
      - if: failure()
        name: "Send GitHub Action trigger failure data to Slack"
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Warning :warning:",
                  }
                },
                {
                  "type": "header",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Scheduled SFTP poller failed :rotating_light:",
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:point_right: Github Actions failure>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}