name: Scheduled External SFTP Poller

on:
  schedule:
    # run every 8 minutes (starting from 4 after each hour)
    - cron: "3/4 * * * *"

jobs:
  run_sftp_poller:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"
      - run: npm ci
      - run: npm run execute ftp-external-poller FMXCHEP
        env:
          STEDI_API_KEY: ${{secrets.STEDI_API_KEY}} # this is the API key for the Stedi user
          DESTINATION_WEBHOOK_URL: ${{secrets.DESTINATION_WEBHOOK_URL}} # something that doesn't need to be changed it seems
          EXECUTIONS_BUCKET_NAME: ${{secrets.EXECUTIONS_BUCKET_NAME }} # this is the bucket where the executions are stored
          SFTP_BUCKET_NAME: ${{secrets.SFTP_BUCKET_NAME }} # this is the bucket where the SFTP files are stored
      # notify via slack if any failures are encountered
      - if: failure()
        name: "Send GitHub Action trigger failed notification to Slack"
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Warning* :warning:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The SFTP poller failed its run. [<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action Run ${{ github.run_id }}>]"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # this is the webhook URL for the Slack channel
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK