name: Scheduled SFTP Polling

on:
  schedule:
    # run every 7 minutes (starting from 3 after each hour)
    - cron: "3/7 * * * *"

jobs:
  run_sftp_poller:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"

      - name: Install Dependencies
        run: npm ci

      - name: Run SFTP Poller For CHEP - LHLN Region
        uses: ./.github/workflows
        with:
          customer_isa_id: FMXCHEP
          stedi_api_key: ${{secrets.STEDI_API_KEY}}
          destination_webhook_url: ${{secrets.DESTINATION_WEBHOOK_URL}}
          executions_bucket_name: ${{secrets.EXECUTIONS_BUCKET_NAME }}
          sftp_bucket_name: ${{secrets.SFTP_BUCKET_NAME }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Run SFTP Poller For CHEP - Other Regions
        if: always()
        uses: ./.github/workflows
        with:
          customer_isa_id: FMXCHEP_OTHER
          stedi_api_key: ${{secrets.STEDI_API_KEY}}
          destination_webhook_url: ${{secrets.DESTINATION_WEBHOOK_URL}}
          executions_bucket_name: ${{secrets.EXECUTIONS_BUCKET_NAME }}
          sftp_bucket_name: ${{secrets.SFTP_BUCKET_NAME }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}